driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['omnibus', '/tmp/omnibus']

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[build]
    attributes:
      omnibus:
        build_iteration: 1
        openssl_fips:
          version: 2.0.16
        # openssl:
        #  version: 1.0.2n # 1.0.2n is already the default version
        nginx:
          version: 1.12.2
