---
driver:
  name: dokken
  privileged: true
  chef_version: latest
  binds:
    - <%= File.expand_path('omnibus') %>:/tmp/omnibus

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[build]
    attributes:
      # Ohai can't find an ipaddress in Dokken
      ipaddress: 127.0.0.1
      omnibus:
        build_iteration: 1
        openssl_fips:
          version: 2.0.16
        # openssl:
        #  version: 1.0.2n # 1.0.2n is already the default version
        nginx:
          version: 1.12.2
