language: ruby

branches:
  only:
    - master

sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

services:
  - docker

install:
  - eval "$(chef shell-init bash)"
  - bundle install

stages:
  - name: test
  - name: build

jobs:
  include:
    - stage: test
      script: rake
    - stage: build
      env:
        - PLATFORM=ubuntu
        - PLATFORM=centos-7
        - PLATFORM=centos-6
      script: kitchen test build-$PLATFORM- && kitchen test verify-$PLATFORM && kitchen test remove-$PLATFORM
